[WIP] Permissions on Resources
marmelab/aor-permissions pull request #22
Opened 2017-07-20 18:32 UTC by djhi

Proposal for applying permissions on the `Resource` component directly.

This addon would provide a custom `Admin` component which can make the necessary asynchronous calls to the authClient to determine whether to display a resource or any of its components.

Resource accepts the following new props:
- `permission`: to define the permissions required for the whole resource
- `listPermission`: to define the permissions required to display the list component
- `createPermission`: to define the permissions required to display the create component
- `editPermission`: to define the permissions required to display the edit component
- `showPermission`: to define the permissions required to display the show component
- `removePermission`: to define the permissions required to display the remove component

Each of these new props should accepts the same values as the others permissions components (single value, array of values or a function).

2017-07-23 19:53 UTC, fzaninotto approved these changes

2017-07-24 11:00 UTC, djhi commented
I'm wondering if I'm taking the right approach here:

I'm not sure having multiple ways to define different action components (list, edit, etc.) depending on user permissions is a good thing. I'm more in favor of defining permissions based resource access inside `Admin` by reusing the `WithPermissions` component:

```jsx
<Admin>
    <WithPermissions>
          <Resource name="customers" />
    </WithPermissions>
    <Resource name="products" />
</Admin>
```

Or eventually, by adding a `ResourceWithPermisions` component:

```jsx
<Admin>
    <ResourceWithPermissions name="customers" permissions="admin" resolve={resolvePermissions} />
    <Resource name="products" />
</Admin>
```

And keep the current way of defining different views depending on permissions as explained in the [readme](https://github.com/marmelab/aor-permissions#usage).

ping @fzaninotto

2017-07-24 11:19 UTC, djhi commented
Another approach would be to reuse the `WithPermissions` and `SwitchPermissions` components:

```jsx
<Admin>
     <WithPermissions permissions="admin">
          <Resource name="customers" />
     </WithPermissions>
     <SwitchPermissions>
          <Permissions permissions="admin">
               <Resource "product" list={...} create={...} /> 
          </Permissions>
          <Permissions permissions="admin">
               <Resource "product" list={...} /> 
          </Permissions>
     </SwitchPermissions>
</Admin>
```

ping @fzaninotto

2017-07-24 15:28 UTC, fzaninotto commented
I love the second approach - it's simple and intuitive. But good luck implementing that - for now, `<Admin>` iterates over its children, expecting resources...

2017-07-24 15:55 UTC, djhi commented
Yes, it implies to keep the `Admin` component supplied by `aor-permissions` as already done in this PR

2017-07-24 16:13 UTC, djhi commented
Unfortunately, this second approach does not allow to specify permissions for each action on a single resource though

2017-07-25 16:35 UTC, djhi commented
Closed as this could be made easier by refactoring the `Resource` component. See #23.

2017-08-01 10:14 UTC, djhi commented
As discussed, we're going back to this implementation due to react-router `Switch` limitations (introspection on its children)

2017-08-03 09:10 UTC, fzaninotto requested changes
Just a little change, otherwise 👍

2017-08-03 09:10 UTC, fzaninotto commented on README.md
> +import { Admin } from 'aor-permissions';
missing `Resource` import

2017-08-03 10:20 UTC, djhi commented on README.md
> +import { Admin } from 'aor-permissions';
Done, imported from `admin-on-rest` on next line

2017-08-03 12:55 UTC, fzaninotto approved these changes

2017-08-03 12:55 UTC, merged